_wandb:
    value:
        cli_version: 0.23.1
        e:
            5p3phfpsvv4chvfq4iuwtluq8ghq32z4:
                apple:
                    ecpuCores: 4
                    gpuCores: 10
                    memoryGb: 8
                    name: Apple M2
                    pcpuCores: 4
                    ramTotalBytes: "8589934592"
                    swapTotalBytes: "5368709120"
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "245107195904"
                        used: "168280797184"
                email: 1546531560@qq.com
                executable: /opt/anaconda3/bin/python
                host: longsiqideMacBook-Air.local
                memory:
                    total: "8589934592"
                os: macOS-15.0.1-arm64-arm-64bit
                program: -m src.train
                python: CPython 3.12.7
                root: /Users/longsiqi/Desktop/Drought_Prediction_LSTM
                startedAt: "2025-12-09T07:23:00.188557Z"
                writerId: 5p3phfpsvv4chvfq4iuwtluq8ghq32z4
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 16
            "4": 3.12.7
            "5": 0.23.1
            "12": 0.23.1
            "13": darwin-arm64
batch_size:
    value: 32
epochs:
    value: 100
learning_rate:
    value: 0.001
seq_length:
    value: 30
